name: GitHub Contributions Reminder

on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST (2:30 AM UTC) - Morning reminder 1
    - cron: '30 4 * * *'   # 10:00 AM IST (4:30 AM UTC) - Morning reminder 2
    - cron: '30 12 * * *'  # 6:00 PM IST (12:30 PM UTC) - Evening reminder 1
    - cron: '30 14 * * *'  # 8:00 PM IST (2:30 PM UTC) - Evening reminder 2
    - cron: '0 16 * * *'   # 9:30 PM IST (4:00 PM UTC) - Night reminder 1
    - cron: '0 17 * * *'   # 10:30 PM IST (5:00 PM UTC) - Night reminder 2
    - cron: '0 18 * * *'   # 11:30 PM IST (6:00 PM UTC) - Night reminder 3
    - cron: '15 18 * * *'  # 11:45 PM IST (6:15 PM UTC) - Night reminder 4
    - cron: '20 18 * * *'  # 11:50 PM IST (6:20 PM UTC) - Night reminder 5
    - cron: '25 18 * * *'  # 11:55 PM IST (6:25 PM UTC) - Night reminder 6
  workflow_dispatch:  # Enable manual trigger

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install any necessary dependencies
          # pip install -r requirements.txt

      - name: Run main.py script
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python src/main.py
